#nlm:
#  name: 'National Library of Medicine. History of Medicine Division'
#  description: 'NLM’s History of Medicine Division collects, preserves, makes available, and interprets for diverse audiences one of the world’s richest collections of historical material related to human health and disease.'
#  building: 'Building 38, Room 1E-21'
#  address1: '8600 Rockville Pike'
#  address2: ''
#  city: 'Bethesda'
#  state: 'MD'
#  zip: '20894'
#  country: 'USA'
#  phone: ''
#  contact_info: 'hmdref@nlm.nih.gov'
#  thumbnail_url: "http://localhost:3000/books.jpg"
#  visit_note: ''
#  request_types:
#    google_form:
#      request_url: 'https://docs.google.com/a/stanford.edu/forms/d/e/1FAIpQLSeOamhY_IcFw4sPnz0ddwWWkrPaHbM5wp7JVbOLOL_mIusEyw/viewform'
#      request_mappings: "document_url=entry.1980510262&collection_name=entry.619150170&collection_creator=entry.14428541&eadid=entry.996397105&containers=entry.1125277048&title=entry.862815208"


#statelib:   
  #count: '596'
  #name: 'Connecticut State Library, State Archives'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ccsu:
#  name:  'Central Connecticut State University'
#  description: ''
#  thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ecsu:
#  name:  'Eastern Connecticut State University'
#  description: ''
#  thumbnail_url: 'http://localhost:3000/books.jpg'
  
#scsu: 
#  name:  'Southern Connecticut State University'
#  description: ''
#  thumbnail_url: 'http://localhost:3000/books.jpg'
  
#wcsu:  
  #name:  'Western Connecticut State University'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#uconn:  
#  name:  'University of Connecticut'
#  description: ''
#  thumbnail_url: 'http://localhost:3000/books.jpg'
  
#litchfield:  
  #name:  'Litchfield Historical Society'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#vhp:  

  #name:  'Veterans History Project, Central Connecticut State University'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  

#yale/vrc:  


#  name:  'Yale University fix'
#  description: ''
#  thumbnail_url: 'http://localhost:3000/books.jpg'
  
#wesleyan:  
  #name:  'Wesleyan Special Collections and Archives'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#CtHi:
#  name:  'Connecticut Historical Society'
#  description: ''
#  thumbnail_url: 'http://localhost:3000/books.jpg'
  
#CtFaHi:  
  #name:  'Fairfield Museum and History Center'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctjhsh:  
  #name:  'Historic New England Library and Archives'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#mystic: 

  #name:  'Mystic River Historical Society'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#hplhhc:  

  #name:  'Hartford Public Library Hartford History Center'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctolfgm   :
  #name:  'Florence Griswold Museum'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctwmhi:  

  #name:  'Mattatuck Museu'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctcwlhs:  

  #name:  'Cornwall Historical Society'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
##cthohs:  

##  name:  'fix'
##  description: ''
##  thumbnail_url: 'http://localhost:3000/books.jpg'
  
#cbict:  

  #name:  'Congregation Beth Israel Archive'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#whartu:  

  #name:  'University of Hartford'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctuh:  
  #count: '4'
  #name:  'Hartford Medical Society'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctcntnm:  

  #name:  'Canton Historical Society'
  #description: 'Canton Historical Society'
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctvernhs:  

  #name:  'Vernon Historical Society'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctGrtAma:  

  #name:  'Avery Memorial Association'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctFmHsm:  

  #name:  'Hill-Stead Museum'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctRiverMuseum:  

  #name:  'Connecticut River Museum'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctedglm:  

  #name:  'Goodspeed Musicals'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#cthwsm:  

  #name:  'Henry Whitfield State Museum'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctlebhs:  

  #name:  'Lebanon Historical Society'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctwlhs:  

  #name:  'Wilton Historical Society'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctwinbml:  

  #name:  'Beardsley & Memorial Library'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctcpcm:  

  #name:  'Prudence Crandall Museum'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctgr:  

  #name: 'Groton Public Library'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctgrotach:  

  #name:  'Avery-Copp House'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctavfpl:  

  #name:  'Avon Free Public Library'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctcovhs:  

  #name:  'Coventry Historical Society'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctivory:  

  #name:  'Ivoryton Library Association'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctwarwhs:  

  #name:  'Warren Historical Society'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctwspwhs:  

  #name: 'Westport Historical Societ'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctelyhs:  

  #name:  'East Lyme Historical Society'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#cthamhi:  

  #name:  'Hamden Historical Society'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#cthhbsc:  

  #name:  'Harriet Beecher Stowe Center'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctwwhpt:  

  #name:  'Wallingford Historical'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#CtB:  

  #name:  'Bridgeport History Center, Bridgeport Public Library'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
#ctsobm:  

  #name:  'Barnes Museum'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
  
#US-CtNIC:

  #name:  'Linda Lear Center for Special Collections and Archives'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
##yale/arts:  

  #name:  'Haas Family Arts Library, Yale University'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
##yale/ycba:  

  #name:  'Center for British Art, Yale University'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
##yale/beinecke:  

##  name:  'Beinecke Rare Book and Manuscript Library, Yale University'
##  description: ''
##  thumbnail_url: 'http://localhost:3000/books.jpg'
  
##yale/divinity:  

  #name:  'Divinity School Library, Yale University'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
##yale/walpole:  

  #name:  'The Lewis Walpole Library, Yale University'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
##yale/med:  

  #name:  'Medical History Library, Yale University'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
##yale/mssa:  

  #name:  'Manuscripts and Archives, Yale University'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
##yale/music:  

  #name:  'Gilmore Music Library, Yale University'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
##yale/peabody:  

  #name:  'Peabody Musum of Natural History, Yale University'
  #description: ''
  #thumbnail_url: 'http://localhost:3000/books.jpg'
  
  
filk:  
  name:  'Harold Stein Filk Archive'
  description: ''
  thumbnail_url: 'http://localhost:3000/books.jpg'
  building: 'Building 38, Room 1E-21'
  address1: '8600 Rockville Pike'
  address2: ''
  city: 'Bethesda'
  state: 'MD'
  zip: '20894'
  country: 'USA'
  phone: ''
  contact_info: 'hmdref@nlm.nih.gov'
  thumbnail_url: "http://localhost:3000/books.jpg"
  visit_note: ''
  #  request_types:
  #    google_form:
  #      request_url: 'https://docs.google.com/a/stanford.edu/forms/d/e/1FAIpQLSeOamhY_IcFw4sPnz0ddwWWkrPaHbM5wp7JVbOLOL_mIusEyw/viewform'
  #      request_mappings: "document_url=entry.1980510262&collection_name=entry.619150170&collection_creator=entry.14428541&eadid=entry.996397105&containers=entry.1125277048&title=entry.862815208"


  